export enum Message {
	SOMETHING_WENT_WRONG = 'Something went wrong!',
	NO_DATA_FOUND = 'No data found!',
	CREATE_FAILED = 'Create operation failed!',
	UPDATE_FAILED = 'Update operation failed!',
	REMOVE_FAILED = 'Remove operation failed!',
	BAD_REQUEST = 'Bad request, Please check your input!',
	UNAUTHORIZED = 'Unauthorized, Please login first!',
	FORBIDDEN = "Forbidden, You don't have permission to access this resource!",

	USED_NICK_PHONE = 'You are inserting already used nick or phone!',
	TOKEN_CREATION_FAILED = 'Token creation failed, Please try again!',
	NO_MEMBER_NICK = 'NO member with that member nick!',
	BLOCKED_USER = 'You have been blocked, contact restaurant',
	WRONG_PSSWORD = 'Wrong password, pleace try again!',
	NOT_AUTHENTICATED = 'You are not authenticated, Please login first!',
	TOKEN_NOT_EXIST = 'Token does not exist, Please login first!',
	ONLY_SPECIFIC_ROLES_ALLOWED = 'Only specific role can access this resource!',
	NOT_ALLOWED_FORMAT = 'You are not allowed to access this resource!',
	SELF_SUBSCRIPTION_DENIED = 'You cannot subscribe to yourself!',
}
